
import { useForm } from "react-hook-form"
import { VehicleDetails, VehicleFormValues } from "../types/vehicleTypes"
import { useEffect } from "react"

export const useVehicleForm = (vehicle: VehicleDetails | null) => {
  const form = useForm<VehicleFormValues>({
    defaultValues: {
      vin: "",
      lot_number: "",
      stock_number: "",
      year: 0,
      destination: "",
      client_name: "",
      client_phone_number: "",
      client_passport_number: "",
      client_buyer_id: "",
      address: "",
      city: "",
      state: "",
      zip_code: "",
      receiver_port_id: 0,
      warehouse_id: 0,
      gate_pass_pin: "",
      is_sublot: false,
      manufacturer_id: 0,
      model_id: 0,
      generation_id: 0,
      body_type_id: 0,
      has_key: false,
      highlights: "",
      auction_id: 0,
      dealer_id: 0,
      sub_dealer_id: 0,
      pay_due_date: "",
      auction_won_price: 0,
      auction_final_price: 0,
      auction_pay_date: "",
      purchase_date: "",
      storage_start_date: "",
      pickup_date: "",
      pickup_date_status: "",
      delivery_date: "",
      delivery_date_status: "",
      transport_listed_price: 0,
      balance_payment_time: "",
      balance_payment_method: "",
      storage_fee: 0,
      company_name: "",
      mc_number: "",
      transporter_name: "",
      transporter_phone: "",
      transporter_payment_date: "",
      shipping_company_name: "",
      shipping_line_id: 0,
      booking_number: "",
      container_number: "",
      receiving_company: "",
      container_load_date: "",
      planned_arrival_date: "",
      container_entry_date: "",
      container_open_date: "",
      green_date: ""
    }
  })

  // Update form values when vehicle data changes
  useEffect(() => {
    if (vehicle) {
      form.reset({
        vin: vehicle.vin || "",
        lot_number: vehicle.lot_number || "",
        stock_number: vehicle.stock_number || "",
        year: vehicle.year || 0,
        destination: vehicle.destination || "",
        client_name: vehicle.client_name || "",
        client_phone_number: vehicle.client_phone_number || "",
        client_passport_number: vehicle.client_passport_number || "",
        client_buyer_id: vehicle.client_buyer_id || "",
        address: vehicle.address || "",
        city: vehicle.city || "",
        state: vehicle.state || "",
        zip_code: vehicle.zip_code || "",
        receiver_port_id: vehicle.receiver_port_id || 0,
        warehouse_id: vehicle.warehouse_id || 0,
        gate_pass_pin: vehicle.gate_pass_pin || "",
        is_sublot: vehicle.is_sublot || false,
        manufacturer_id: vehicle.manufacturer_id || 0,
        model_id: vehicle.model_id || 0,
        generation_id: vehicle.generation_id || 0,
        body_type_id: vehicle.body_type_id || 0,
        has_key: vehicle.has_key || false,
        highlights: vehicle.highlights || "",
        auction_id: vehicle.auction_id || 0,
        dealer_id: vehicle.dealer_id || 0,
        sub_dealer_id: vehicle.sub_dealer_id || 0,
        pay_due_date: vehicle.pay_due_date || "",
        auction_won_price: vehicle.auction_won_price || 0,
        auction_final_price: vehicle.auction_final_price || 0,
        auction_pay_date: vehicle.auction_pay_date || "",
        purchase_date: vehicle.purchase_date || "",
        storage_start_date: vehicle.storage_start_date || "",
        pickup_date: vehicle.pickup_date || "",
        pickup_date_status: vehicle.pickup_date_status || "",
        delivery_date: vehicle.delivery_date || "",
        delivery_date_status: vehicle.delivery_date_status || "",
        transport_listed_price: vehicle.transport_listed_price || 0,
        balance_payment_time: vehicle.balance_payment_time || "",
        balance_payment_method: vehicle.balance_payment_method || "",
        storage_fee: vehicle.storage_fee || 0,
        company_name: vehicle.company_name || "",
        mc_number: vehicle.mc_number || "",
        transporter_name: vehicle.transporter_name || "",
        transporter_phone: vehicle.transporter_phone || "",
        transporter_payment_date: vehicle.transporter_payment_date || "",
        shipping_company_name: vehicle.shipping_company_name || "",
        shipping_line_id: vehicle.shipping_line_id || 0,
        booking_number: vehicle.booking_number || "",
        container_number: vehicle.container_number || "",
        receiving_company: vehicle.receiving_company || "",
        container_load_date: vehicle.container_load_date || "",
        planned_arrival_date: vehicle.planned_arrival_date || "",
        container_entry_date: vehicle.container_entry_date || "",
        container_open_date: vehicle.container_open_date || "",
        green_date: vehicle.green_date || ""
      })
    }
  }, [vehicle, form])

  return form
}
