
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brfijmanqmhcbfjewfts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZmlqbWFucW1oY2JmamV3ZnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5ODM3NDIsImV4cCI6MjA1NjU1OTc0Mn0.OiDK11UXExlg1k51njTWGz3tjB08oswVd3Mep54CJ4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
